title: Land Transport Innovation Portal
url: ""
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#4a4a4a"
  secondary-color: "#2a517f"
  media-colors:
    - title: media-color-one
      color: "#9b9b9b"
    - title: media-color-two
      color: "#50e3c2"
    - title: media-color-three
      color: "#f6cd88"
    - title: media-color-four
      color: "#ff8e8e"
    - title: media-color-five
      color: "#f2e980"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://lta-ltinnovation-staging.netlify.app
prod: https://lta-ltinnovation-prod.netlify.app
shareicon: ""
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
